name: 🪄 Caching ✨magic✨
on:
  push:
    branches:
      - demo-ci
  pull_request: {}
permissions:
  actions: write
  contents: read

jobs:
  withcache:
    name: 🪄 With Cache !
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'
      - run: npm ci
      - run: npm run test
  
  withoutcache:
    name: 🛑 Without Cache !
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test
  